version: '3'

services:
  backend:
    build:
      context: .
    ports:
      - "5000:5000"
    depends_on:
      - database

  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: Winstrike
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 11111111
    restart: always